"""Added fields

Revision ID: 428036391854
Revises: 5ba58c3afca1
Create Date: 2025-09-28 14:56:39.293082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "428036391854"
down_revision: Union[str, Sequence[str], None] = "5ba58c3afca1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employers", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("employers", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("vacancies", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("vacancies", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancies", "updated_at")
    op.drop_column("vacancies", "created_at")
    op.drop_column("employers", "updated_at")
    op.drop_column("employers", "created_at")
    # ### end Alembic commands ###
