"""init tables

Revision ID: 4e2975322c6e
Revises: 428036391854
Create Date: 2025-09-29 18:30:56.733663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e2975322c6e"
down_revision: Union[str, Sequence[str], None] = "428036391854"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vacancies", sa.Column("summary", sa.Text(), nullable=True))
    op.drop_column("vacancies", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vacancies",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("vacancies", "summary")
    # ### end Alembic commands ###
