"""init tables

Revision ID: e181e9a37a34
Revises: 4e2975322c6e
Create Date: 2025-09-29 19:17:06.709268

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e181e9a37a34"
down_revision: Union[str, Sequence[str], None] = "4e2975322c6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
